// ============================================
//  DEEP REFLECTION QUESTIONS (left reel)
// ============================================
const DEEP_QUESTIONS = [
  // Life & meaning
  "If your life were a book, what would the title of this current chapter be?",
  "What does a 'meaningful' day look like to you, in concrete detail?",
  "If you could live your last year over again, what would you do differently?",
  "What part of who you are today would your 10-year-old self be proud of?",
  "What part of who you are today would your 10-year-old self be confused by?",
  "If you knew you couldn't fail, what would you start tomorrow?",
  "What is something you believe deeply that you can't prove?",
  "What does 'home' mean to you right now, beyond a physical place?",
  "If you had to teach one lesson to a younger version of yourself, what would it be?",
  "What is one small thing that consistently makes you feel alive?",
  "What would you do with a completely free, unstructured month?",
  "Whose life are you secretly comparing yours to, and why?",
  "What does success look like when no one is watching?",
  "If your values were a recipe, what would the main ingredients be?",
  "What part of your life feels most like it's on autopilot?",

  // Emotion awareness
  "What emotion have you been avoiding lately, and what is it trying to tell you?",
  "When did you last cry, and what was it really about?",
  "What's the difference between how you felt today and how you said you felt?",
  "Where in your body do you feel stress most often? What does it feel like?",
  "What's something that made you smile this week that surprised you?",
  "What feeling are you most uncomfortable letting other people see?",
  "When was the last time you felt completely at peace? What conditions made that possible?",
  "What does loneliness feel like for you, specifically?",
  "If your current mood had a color and a sound, what would they be?",
  "What is one feeling you wish you could feel more often?",
  "What's a compliment you received that you didn't quite believe?",
  "What angers you that probably shouldn't, and what's underneath the anger?",
  "What does anxiety try to protect you from?",
  "When do you feel most like yourself?",
  "What's an emotion you're grateful you've gotten better at handling?",

  // Relationships
  "Who in your life have you been taking for granted?",
  "What would you say to someone you've lost, if you could send one message?",
  "Who is someone you think about often but rarely contact? Why?",
  "What kind of friend are you, and what kind of friend do you want to be?",
  "What's a relationship pattern you've noticed in your own life?",
  "When did someone last truly listen to you? How did it feel?",
  "What's something you've never told anyone, and why?",
  "Who has shaped your idea of love, for better or worse?",
  "What do you need from the people closest to you that you haven't asked for?",
  "What's a kindness you've received that you've never been able to repay?",
  "Who do you become around your family that you aren't elsewhere?",
  "What does forgiveness mean to you — and is there someone you're still working on forgiving?",
  "Who in your life expands you, and who shrinks you?",
  "What's an old friendship you mourn the loss of?",
  "What's one thing you've never thanked your past self for?",

  // Curiosity & imagination
  "If you could have one superpower, what would it be — and what would you actually use it for in your daily life?",
  "If you woke up tomorrow with one new skill mastered, what would you choose and why?",
  "What's a question you've been afraid to ask?",
  "If your dreams were trying to send you a message, what do you think it would be?",
  "What's something 'weird' you secretly love?",
  "If you could time-travel for one day with no ability to change anything, where would you go?",
  "What's a future you imagine for yourself that you've never said out loud?",
  "If you could invent a holiday, what would it celebrate and how?",
  "What's a wild idea you've had recently that you dismissed too quickly?",
  "If you had to design a museum about your life, what would the first exhibit be?",
  "What invention do you wish existed?",
  "If you could send one object 1000 years into the future, what would it be?",
  "If your inner critic had a name and a face, what would they look like?",
  "What's an alternate life path you sometimes imagine?",
  "If you had to live in a single decade (past or future), which one and why?",

  // Habits, body & daily life
  "What's one small habit that has changed your life more than you expected?",
  "If your body could write you a letter today, what would it say?",
  "What's something you do daily that you rarely think about — and what would change if you paid attention to it?",
  "What's a 'small luxury' in your life that you'd defend fiercely?",
  "What does rest actually look like for you — not what you tell yourself it should look like?",
  "What part of your morning routine sets the tone for the rest of your day?",
  "What's a way you're kind to yourself that you wish you'd discovered sooner?",
  "What's something you used to love doing that you've stopped — for no clear reason?",
  "If you tracked your screen time honestly, what would surprise you?",
  "When was the last time you were bored, and what did boredom give you?",
  "What's the relationship between you and sleep right now?",
  "What food gives you a feeling of being cared for?",
  "What's a tiny ritual that brings you joy?",
  "If today had a soundtrack, what's the first song on it?",
  "What's the most beautiful thing you noticed this week?",

  // Fear & growth
  "What's a fear you've outgrown, and how did that happen?",
  "What's a fear you'd like to outgrow?",
  "What's something you're proud of that took a long time?",
  "When did you last surprise yourself?",
  "What feedback have you received that stung, but turned out to be true?",
  "What's something you've quit that you're now proud of quitting?",
  "What's a 'failure' that, looking back, you wouldn't undo?",
  "What do you want to be different about your life one year from now?",
  "What's something you keep starting and never finishing? Why?",
  "What would you attempt if you knew it was okay to be bad at it?",
  "Where in your life are you brave without realizing it?",
  "What's a risk that didn't work out, but taught you something?",
  "What's an old story you tell about yourself that may no longer be true?",
  "What does 'enough' mean to you, in a world that always asks for more?",
  "What's something you used to believe was a flaw that you now see differently?",

  // Work & purpose
  "If money truly weren't a factor, how would you spend your weekdays?",
  "What kind of work makes time disappear for you?",
  "What part of your work do you find quietly meaningful?",
  "What's something you're good at that you don't take credit for?",
  "What does 'ambition' mean to you right now — has its meaning shifted?",
  "Who do you secretly want to be seen by, in your work?",
  "What would 'enough' professional success look like for you?",
  "What's a project you'd start if no one would judge it?",
  "Where do you feel most useful?",
  "If you had to write your own job description, what would it actually say?",

  // Memory & identity
  "What's a memory that feels like it belongs to a different version of you?",
  "What's a smell that always takes you somewhere else?",
  "What's something you remember vividly that no one else would?",
  "What object in your home holds the most story?",
  "What's a song that, when you hear it, you become a younger version of yourself?",
  "Whose voice plays in your head most often?",
  "What's something your culture taught you that you've kept, and what have you released?",
  "What part of your identity feels chosen, and what part feels inherited?",
  "What's a place you've only visited once that you still think about?",
  "What's a small moment of beauty you've never told anyone about?",

  // Gratitude & presence
  "What's something ordinary you'd miss terribly if it were gone?",
  "Who made your life easier today, even slightly?",
  "What part of your body have you been ungrateful for?",
  "What's a way the world has surprised you lately, in a good way?",
  "What did you almost not do today, but did anyway?",
  "What's a privilege in your life you've stopped noticing?",
  "What's something you've gotten better at without trying?",
  "What part of today would you save in a tiny glass jar?",
  "What's a recent moment you wish you'd been more present for?",
  "What's something you used to want desperately that you now have?",
  "What's one thing about right now — exactly now — that's actually okay?",
  "If you wrote a thank-you note today, who would it be to and what would it say?",
  "What's been quietly going right in your life that you haven't acknowledged?",
];

// ============================================
//  SIMPLE DAILY QUESTIONS (right reel)
//  Easy, warm, everyday prompts to balance the deeper one
// ============================================
const SIMPLE_QUESTIONS = [
  "How do you feel today? Name one word.",
  "What was the happiest moment today, even a tiny one?",
  "What did you eat that you actually enjoyed today?",
  "What's the weather doing where you are?",
  "What's the first thing you noticed when you woke up?",
  "Who did you talk to today?",
  "What made you laugh recently?",
  "What's one small thing that went well today?",
  "What are you looking forward to this week?",
  "Did you go outside today? How was it?",
  "What's something you're wearing today that you like?",
  "What's a sound you noticed today?",
  "What's a color you saw a lot of today?",
  "What did you drink today? Was it good?",
  "Are you tired right now? On a scale of 1–10?",
  "What's the last song you listened to?",
  "What's been on your mind in the background today?",
  "What's one thing you finished today, big or small?",
  "What did your body need today that you gave it (or didn't)?",
  "Who texted or called you today?",
  "What's the last thing that made you smile?",
  "What's one thing you saw outside today?",
  "What's something kind you did today (for yourself or someone else)?",
  "What's been frustrating today?",
  "What time did you wake up? How did you feel about it?",
  "What's one thing you're grateful for right now?",
  "What's the messiest spot in your space today?",
  "Did you move your body today? How?",
  "What's a smell you noticed today?",
  "What's a tiny win from today?",
  "What's something you wish you'd done differently today?",
  "What's a phrase you said (or heard) a lot today?",
  "What did you scroll past that stuck with you?",
  "How is your energy right now? Like a battery percentage.",
  "What's one thing you're putting off?",
  "What's a small comfort you're enjoying right now?",
  "Did you learn anything new today, even something tiny?",
  "What's the most beautiful thing you saw today?",
  "Who made today easier for you?",
  "What's something you want to remember about today?",
  "What's something you'd like to leave behind today?",
  "What did you say 'yes' to today? What did you say 'no' to?",
  "If today were a flavor, what would it taste like?",
  "What's the temperature of your mood right now?",
  "What's one thing you want to do before bed?",
  "What does the inside of your head sound like right now?",
  "What's a tiny pleasure you've had today?",
  "What's the last photo you took? Why did you take it?",
  "What's been the easiest part of today?",
  "What's been the hardest part of today?",
  "What time is it where you are, and how do you feel about it?",
  "What did your morning look like today?",
  "What does the rest of today look like for you?",
  "What's a sentence you'd write on a postcard about today?",
  "If your day were weather, what would the forecast say?",
  "What's a thought that keeps looping today?",
  "How does your space feel today — cozy, cluttered, calm, chaotic?",
  "What's something you noticed about a stranger today?",
  "Did you laugh out loud today? At what?",
  "What's the best thing you ate this week?",
  "What's a small habit you actually did today?",
  "What's something you'd like more of tomorrow?",
];

// Backwards-compat alias (older code refers to QUESTIONS)
const QUESTIONS = [...DEEP_QUESTIONS, ...SIMPLE_QUESTIONS];

// 60+ research topics — single words or short phrases the user can dig into
const RESEARCH_TOPICS = [
  "Sadness",
  "Sustainability",
  "Dogs",
  "Solar power",
  "Culture shock",
  "Loneliness",
  "Sleep",
  "Tides",
  "Nostalgia",
  "Salt",
  "Honeybees",
  "Silence",
  "Forgetting",
  "Color blue",
  "Maps",
  "Cathedrals",
  "Tea",
  "Mushrooms",
  "Money",
  "Migration",
  "Boredom",
  "Mirrors",
  "Octopus cognition",
  "Time zones",
  "Glaciers",
  "Handwriting",
  "Folk music",
  "Public libraries",
  "Garbage",
  "Forests",
  "Bread",
  "Insomnia",
  "Photography",
  "Bicycles",
  "Aging",
  "Rivers",
  "Friendship",
  "Languages dying out",
  "Wind",
  "Tattoos",
  "Sourdough",
  "Birds of your city",
  "Concrete",
  "Sunflowers",
  "Memory palaces",
  "Daydreaming",
  "Subway systems",
  "Stars you can see tonight",
  "Smiling",
  "Rust",
  "Spices",
  "Mountains",
  "Dreams",
  "Smell",
  "Coffee",
  "Walking",
  "Rain",
  "Origami",
  "Lighthouses",
  "Bookshops",
  "Knots",
  "Gardens",
  "Volcanoes",
  "Whales",
  "Bridges",
];
